name: swatantratech
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_core: ^2.1.0
  firebase_auth: ^4.0.2
  material_dialogs: ^1.1.3
  get: ^4.1.4
  lottie: ^1.4.3
  oktoast: ^3.3.1
  gender_picker: ^1.1.0
  date_time_picker: ^2.1.0
  image_picker: ^0.8.6
  modal_bottom_sheet: ^2.1.2
  cloud_firestore: ^4.0.2
  image_cropper: ^3.0.0
  firebase_storage: ^11.0.2
  simple_fontellico_progress_dialog: ^0.2.1
  cached_network_image: ^3.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/lottie/